abbreviation_dict = {"by mouth":["PO","Po","po"],
                    "drops":["gtt"],
                    "female":["F"],
                    "heart rate":["HR"],
                    "history":["hx"],
                    "male":["M"],
                    "normal saline":["NS"],
                    "oxygen saturation":["O2 sat","O2 sats"],
                    "percutaneous endoscopic gastrostomy tube placment":["PEG"],
                    "patient":["pt.","pt"],
                    "Patient":["Pt.","Pt","PT"],
                    "patient's":["pts.","pts"],
                    "Patient's":["Pts.","Pts"],
                    "pro re nata":["PRN.","prn.","PRN","prn",], 
                    "previous medical history":["PMHx"],
                    "significant":["sig."],
                    "status post":["s/p"],
                    "systolic blood pressure":["SBP"],
                    "tracheostomy":["trach"],
                    "ultrasound":["U/S"],
                    "with":["w/","W/"],
                    "without":["w/o","W/o","W/O"],
                    "year old":["yo","y/o","YO"],
                    }